type PostCommands =
  | string
  | "crm.settings.mode.get"
  //endregion

  //region Status
  | "crm.status.fields"
  | "crm.status.add"
  | "crm.status.get"
  | "crm.status.list"
  | "crm.status.update"
  | "crm.status.delete"
  | "crm.status.entity.types"
  | "crm.status.entity.items"
  | "crm.status.extra.fields"
  | "crm.invoice.status.fields"
  | "crm.invoice.status.add"
  | "crm.invoice.status.get"
  | "crm.invoice.status.list"
  | "crm.invoice.status.update"
  | "crm.invoice.status.delete"
  //endregion
  //region Enumeration
  | "crm.enum.settings.mode"
  | "crm.enum.fields"
  | "crm.enum.ownertype"
  | "crm.enum.addresstype"
  | "crm.enum.contenttype"
  | "crm.enum.activitytype"
  | "crm.enum.activitypriority"
  | "crm.enum.activitydirection"
  | "crm.enum.activitynotifytype"
  | "crm.enum.activitystatus"
  | "crm.enum.entityeditor.configuration.scope"
  //endregion
  //region Lead
  | "crm.lead.fields"
  | "crm.lead.add"
  | "crm.lead.get"
  | "crm.lead.list"
  | "crm.lead.update"
  | "crm.lead.delete"
  | "crm.lead.productrows.set"
  | "crm.lead.productrows.get"
  //endregion
  //region Deal
  | "crm.deal.fields"
  | "crm.deal.add"
  | "crm.deal.get"
  | "crm.deal.list"
  | "crm.deal.update"
  | "crm.deal.delete"
  | "crm.deal.productrows.set"
  | "crm.deal.productrows.get"
  | "crm.deal.contact.fields"
  | "crm.deal.contact.add"
  | "crm.deal.contact.delete"
  | "crm.deal.contact.items.get"
  | "crm.deal.contact.items.set"
  | "crm.deal.contact.items.delete"
  //endregion
  //region Deal Category
  | "crm.dealcategory.fields"
  | "crm.dealcategory.list"
  | "crm.dealcategory.add"
  | "crm.dealcategory.get"
  | "crm.dealcategory.update"
  | "crm.dealcategory.delete"
  | "crm.dealcategory.status"
  | "crm.dealcategory.stage.list"
  | "crm.dealcategory.default.get"
  | "crm.dealcategory.default.set"
  //endregion
  //region Deal Recurring
  | "crm.deal.recurring.fields"
  | "crm.deal.recurring.list"
  | "crm.deal.recurring.add"
  | "crm.deal.recurring.get"
  | "crm.deal.recurring.update"
  | "crm.deal.recurring.delete"
  | "crm.deal.recurring.expose"
  //endregion
  //region Invoce Recurring
  | "crm.invoice.recurring.fields"
  | "crm.invoice.recurring.list"
  | "crm.invoice.recurring.add"
  | "crm.invoice.recurring.get"
  | "crm.invoice.recurring.update"
  | "crm.invoice.recurring.delete"
  | "crm.invoice.recurring.expose"
  //endregion
  //region Company
  | "crm.company.fields"
  | "crm.company.add"
  | "crm.company.get"
  | "crm.company.list"
  | "crm.company.update"
  | "crm.company.delete"
  | "crm.company.contact.fields"
  | "crm.company.contact.add"
  | "crm.company.contact.delete"
  | "crm.company.contact.items.get"
  | "crm.company.contact.items.set"
  | "crm.company.contact.items.delete"
  //endregion
  //region Contact
  | "crm.contact.fields"
  | "crm.contact.add"
  | "crm.contact.get"
  | "crm.contact.list"
  | "crm.contact.update"
  | "crm.contact.delete"
  | "crm.contact.company.fields"
  | "crm.contact.company.add"
  | "crm.contact.company.delete"
  | "crm.contact.company.items.get"
  | "crm.contact.company.items.set"
  | "crm.contact.company.items.delete"
  //endregion
  //region Currency
  | "crm.currency.fields"
  | "crm.currency.add"
  | "crm.currency.get"
  | "crm.currency.list"
  | "crm.currency.update"
  | "crm.currency.delete"
  | "crm.currency.localizations.fields"
  | "crm.currency.localizations.get"
  | "crm.currency.localizations.set"
  | "crm.currency.localizations.delete"
  | "crm.currency.base.set"
  | "crm.currency.base.get"
  //endregion
  //region Catalog
  | "crm.catalog.fields"
  | "crm.catalog.get"
  | "crm.catalog.list"
  //endregion
  //region Product
  | "crm.product.fields"
  | "crm.product.add"
  | "crm.product.get"
  | "crm.product.list"
  | "crm.product.update"
  | "crm.product.delete"
  //endregion
  //region Product Property
  | "crm.product.property.types"
  | "crm.product.property.fields"
  | "crm.product.property.settings.fields"
  | "crm.product.property.enumeration.fields"
  | "crm.product.property.add"
  | "crm.product.property.get"
  | "crm.product.property.list"
  | "crm.product.property.update"
  | "crm.product.property.delete"
  //endregion
  //region Product Section
  | "crm.productsection.fields"
  | "crm.productsection.add"
  | "crm.productsection.get"
  | "crm.productsection.list"
  | "crm.productsection.update"
  | "crm.productsection.delete"
  //endregion
  //region Product Row
  | "crm.productrow.fields"
  | "crm.productrow.add"
  | "crm.productrow.get"
  | "crm.productrow.list"
  | "crm.productrow.update"
  | "crm.productrow.delete"
  //endregion
  //region Activity
  | "crm.activity.fields"
  | "crm.activity.add"
  | "crm.activity.get"
  | "crm.activity.list"
  | "crm.activity.update"
  | "crm.activity.delete"
  | "crm.activity.communication.fields"
  //endregion
  //region Activity Type
  | "crm.activity.type.add"
  | "crm.activity.type.list"
  | "crm.activity.type.delete"
  //endregion
  //region Quote
  | "crm.quote.fields"
  | "crm.quote.add"
  | "crm.quote.get"
  | "crm.quote.list"
  | "crm.quote.update"
  | "crm.quote.delete"
  | "crm.quote.productrows.set"
  | "crm.quote.productrows.get"
  | "crm.quote.contact.fields"
  | "crm.quote.contact.add"
  | "crm.quote.contact.delete"
  | "crm.quote.contact.items.get"
  | "crm.quote.contact.items.set"
  | "crm.quote.contact.items.delete"
  //endregion
  //region Requisite
  | "crm.requisite.fields"
  | "crm.requisite.add"
  | "crm.requisite.get"
  | "crm.requisite.list"
  | "crm.requisite.update"
  | "crm.requisite.delete"
  //
  | "crm.requisite.userfield.add"
  | "crm.requisite.userfield.get"
  | "crm.requisite.userfield.list"
  | "crm.requisite.userfield.update"
  | "crm.requisite.userfield.delete"
  //
  | "crm.requisite.preset.fields"
  | "crm.requisite.preset.add"
  | "crm.requisite.preset.get"
  | "crm.requisite.preset.list"
  | "crm.requisite.preset.update"
  | "crm.requisite.preset.delete"
  | "crm.requisite.preset.countries"
  //
  | "crm.requisite.preset.field.fields"
  | "crm.requisite.preset.field.availabletoadd"
  | "crm.requisite.preset.field.add"
  | "crm.requisite.preset.field.get"
  | "crm.requisite.preset.field.list"
  | "crm.requisite.preset.field.update"
  | "crm.requisite.preset.field.delete"
  //
  | "crm.requisite.bankdetail.fields"
  | "crm.requisite.bankdetail.add"
  | "crm.requisite.bankdetail.get"
  | "crm.requisite.bankdetail.list"
  | "crm.requisite.bankdetail.update"
  | "crm.requisite.bankdetail.delete"
  //
  | "crm.requisite.link.fields"
  | "crm.requisite.link.list"
  | "crm.requisite.link.get"
  | "crm.requisite.link.register"
  | "crm.requisite.link.unregister"
  //endregion Requisite
  //region Address
  | "crm.address.fields"
  | "crm.address.add"
  | "crm.address.update"
  | "crm.address.list"
  | "crm.address.delete"
  | "crm.address.getzoneid"
  | "crm.address.setzoneid"
  //endregion Address
  //region Address type
  | "crm.addresstype.getavailable"
  | "crm.addresstype.getzonemap"
  | "crm.addresstype.getdefaultbyzone"
  | "crm.addresstype.getbyzonesorvalues"
  //endregion Address type
  //region Measures
  | "crm.measure.fields"
  | "crm.measure.add"
  | "crm.measure.get"
  | "crm.measure.list"
  | "crm.measure.update"
  | "crm.measure.delete"
  //endregion Measures

  //region User Field
  | "crm.lead.userfield.add"
  | "crm.lead.userfield.get"
  | "crm.lead.userfield.list"
  | "crm.lead.userfield.update"
  | "crm.lead.userfield.delete"
  | "crm.deal.userfield.add"
  | "crm.deal.userfield.get"
  | "crm.deal.userfield.list"
  | "crm.deal.userfield.update"
  | "crm.deal.userfield.delete"
  | "crm.company.userfield.add"
  | "crm.company.userfield.get"
  | "crm.company.userfield.list"
  | "crm.company.userfield.update"
  | "crm.company.userfield.delete"
  | "crm.contact.userfield.add"
  | "crm.contact.userfield.get"
  | "crm.contact.userfield.list"
  | "crm.contact.userfield.update"
  | "crm.contact.userfield.delete"
  | "crm.quote.userfield.add"
  | "crm.quote.userfield.get"
  | "crm.quote.userfield.list"
  | "crm.quote.userfield.update"
  | "crm.quote.userfield.delete"
  | "crm.invoice.userfield.add"
  | "crm.invoice.userfield.get"
  | "crm.invoice.userfield.list"
  | "crm.invoice.userfield.update"
  | "crm.invoice.userfield.delete"
  | "crm.userfield.fields"
  | "crm.userfield.types"
  | "crm.userfield.enumeration.fields"
  | "crm.userfield.settings.fields"
  //endregion

  //region Externalchannel connector.
  | "crm.externalchannel.connector.fields"
  | "crm.externalchannel.connector.list"
  | "crm.externalchannel.connector.register"
  | "crm.externalchannel.connector.unregister"
  //endregion

  //region Misc.
  | "crm.multifield.fields"
  | "crm.duplicate.findbycomm"
  | "crm.livefeedmessage.add"
  | "crm.externalchannel.company"
  | "crm.externalchannel.contact"
  | "crm.externalchannel.activity.company"
  | "crm.externalchannel.activity.contact"
  | "crm.webform.configuration.get"
  | "crm.sitebutton.configuration.get"
  | "crm.persontype.fields"
  | "crm.persontype.list"
  | "crm.paysystem.fields"
  | "crm.paysystem.list"
  //endregion
  //region Automation
  | "crm.automation.trigger"
  | "crm.automation.trigger.add"
  | "crm.automation.trigger.list"
  | "crm.automation.trigger.delete"
  | "crm.automation.trigger.execute"
  //endregion
  //region Timeline
  | "crm.timeline.comment.fields"
  | "crm.timeline.comment.add"
  | "crm.timeline.comment.list"
  | "crm.timeline.comment.get"
  | "crm.timeline.comment.delete"
  | "crm.timeline.comment.update"
  | "crm.timeline.bindings.fields"
  | "crm.timeline.bindings.list"
  | "crm.timeline.bindings.bind"
  | "crm.timeline.bindings.unbind"
  //endregion
  //region Details Page Configuration
  | "crm.lead.details.configuration.get"
  | "crm.lead.details.configuration.set"
  | "crm.lead.details.configuration.reset"
  | "crm.lead.details.configuration.forceCommonScopeForAll"
  | "crm.deal.details.configuration.get"
  | "crm.deal.details.configuration.set"
  | "crm.deal.details.configuration.reset"
  | "crm.deal.details.configuration.forceCommonScopeForAll"
  | "crm.contact.details.configuration.get"
  | "crm.contact.details.configuration.set"
  | "crm.contact.details.configuration.reset"
  | "crm.contact.details.configuration.forceCommonScopeForAll"
  | "crm.company.details.configuration.get"
  | "crm.company.details.configuration.set"
  | "crm.company.details.configuration.reset"
  | "crm.company.details.configuration.forceCommonScopeForAll";
